/* Bundle for CDN. This is packaging, not compilation — src/largen.css is valid
 * CSS and works as-is. Anything that made this step mandatory would be a design
 * failure, so the sizes below are informational, not a gate.
 *
 * It uses no third-party code. That is the point rather than an economy: a
 * library whose first sentence is "no build step, no preprocessor, no plugin"
 * should not need a Rust CSS toolchain on the host that publishes it. See
 * bundle.mjs for what was measured before removing the one that used to be here.
 *
 * TWO HASHES, TWO JOBS
 *
 * The banner carries a build id: the hash of the bundle BEFORE the banner is
 * prepended. It has to be the body's hash, not the file's, or it is circular —
 * putting a file's hash inside that file changes the file's hash. It answers
 * "which build am I looking at?" from the file alone.
 *
 * build.json carries the sha256 of the SERVED BYTES, banner included, plus the
 * same digest in SRI form. That is the one to record when vendoring, and the one
 * `curl | shasum` reproduces.
 *
 * Publishing both without saying which is which would be worse than publishing
 * neither, so build.json labels them.
 */
import { gzipSync } from 'node:zlib'
import { createHash } from 'node:crypto'
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { root } from './paths.mjs'
import { bundle } from './bundle.mjs'

const kb = (n) => (n / 1024).toFixed(2) + 'kb'
const sha256 = (buf) => createHash('sha256').update(buf).digest('hex')
const sri = (buf) => 'sha384-' + createHash('sha384').update(buf).digest('base64')

const PROFILES = [
  ['largen.css', 'src/largen.css', 'the algebra + layout utilities — all you need'],
  ['largen.components.css', 'components/index.css', 'optional reference components'],
  ['theme-dark.css', 'themes/dark.css', 'eleven token overrides'],
  ['site-example.css', 'sites/example/index.css', "a whole site: algebra + prose + theme + its own components"],
]

export async function build() {
  const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

  mkdirSync(join(root, 'dist'), { recursive: true })
  console.log('\n  largen build — concatenation and minification, not compilation\n')

  const files = {}
  let buildId = null

  for (const [out, entry, note] of PROFILES) {
    /* The last profile bundles sites/example, which is a demonstration and is
       deliberately absent from the published package. Skipping a missing entry
       keeps `largen build` working from an install; failing on it would make a
       shipped command depend on a file the package does not ship. */
    if (!existsSync(join(root, entry))) {
      console.log(`  ${out.padEnd(24)} ${'skipped'.padStart(9)}             not in this package (${entry})`)
      continue
    }
    const body = bundle(join(root, entry))
    /* The entry point's body hash names the build. Deterministic: identical
       source gives an identical id, so a rebuild that changes nothing is
       visibly a no-op. */
    const id = sha256(body).slice(0, 8)
    if (out === 'largen.css') buildId = id

    const banner = `/*! largen ${version}+${id} | MIT | https://largen.dev */`
    const code = `${banner}\n${body}`
    writeFileSync(join(root, 'dist', out), code)

    const buf = Buffer.from(code)
    files[out] = { bytes: buf.length, build: id, sha256: sha256(buf), integrity: sri(buf) }

    console.log(`  ${out.padEnd(24)} ${kb(code.length).padStart(9)} ${kb(gzipSync(code).length).padStart(9)} gz  ${id}`)
    console.log(`  ${''.padEnd(24)} ${note}`)
  }

  const manifest = {
    $comment:
      'Generated by `largen build`. `sha256` and `integrity` are of the served ' +
      'bytes, banner included — these are what `curl | shasum -a 256` reproduces ' +
      'and what to record when vendoring. `build` is the hash of the bundle before ' +
      'the banner was added, which is what the banner itself prints; it names the ' +
      'build but is not the file digest. The unversioned paths are not immutable: ' +
      'pin by sha256, by integrity, or use a /v/<version>/ path.',
    version,
    build: buildId,
    files,
  }
  writeFileSync(join(root, 'dist', 'build.json'), JSON.stringify(manifest, null, 2) + '\n')
  console.log(`\n  build.json               ${buildId}  (sha256 + SRI for each file)\n`)
}
