/* Bundle for CDN. This is packaging, not compilation — src/largen.css is valid
 * CSS and works as-is. Anything that made this step mandatory would be a design
 * failure, so the sizes below are informational, not a gate.
 *
 * It uses no third-party code. That is the point rather than an economy: a
 * library whose first sentence is "no build step, no preprocessor, no plugin"
 * should not need a Rust CSS toolchain on the host that publishes it. See
 * bundle.mjs for what was measured before removing the one that used to be here.
 *
 * TWO HASHES, TWO JOBS
 *
 * The banner carries a build id: the hash of the bundle BEFORE the banner is
 * prepended. It has to be the body's hash, not the file's, or it is circular —
 * putting a file's hash inside that file changes the file's hash. It answers
 * "which build am I looking at?" from the file alone.
 *
 * build.json carries the sha256 of the SERVED BYTES, banner included, plus the
 * same digest in SRI form. That is the one to record when vendoring, and the one
 * `curl | shasum` reproduces.
 *
 * Publishing both without saying which is which would be worse than publishing
 * neither, so build.json labels them.
 *
 * TWO KINDS OF PROFILE
 *
 * Most profiles bundle CSS. Two export DTCG token documents instead, derived
 * from the same stylesheets: src/tokens.css becomes dist/largen.tokens.json and
 * themes/dark.css becomes dist/theme-dark.tokens.json. The CSS stays the source
 * of truth — `largen verify` fails if the documents drift from it.
 *
 * Those two carry no banner, because a comment is not JSON and a consumer
 * pipeline parses these rather than reading them. Their provenance is inside
 * the document instead, in $extensions["dev.largen"]: the library version, the
 * largen.css build id, the DTCG draft they target, the theme and the colour
 * scheme. They are recorded in build.json with the same digests as the
 * stylesheets, so vendoring one is pinnable the same way.
 */
import { gzipSync } from 'node:zlib'
import { createHash } from 'node:crypto'
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { root } from './paths.mjs'
import { bundle } from './bundle.mjs'
import { parseTokensCss, toDtcg } from '../../genai/tokens.js'

const kb = (n) => (n / 1024).toFixed(2) + 'kb'
const sha256 = (buf) => createHash('sha256').update(buf).digest('hex')
const sri = (buf) => 'sha384-' + createHash('sha384').update(buf).digest('base64')

/* [output, entry, note, kind]. The token documents come after largen.css
   because they record its build id, and site-example stays last because it is
   the one profile the published package does not ship. */
const PROFILES = [
  ['largen.css', 'src/largen.css', 'the algebra + layout utilities — all you need', 'css'],
  ['largen.components.css', 'components/index.css', 'optional reference components', 'css'],
  ['theme-dark.css', 'themes/dark.css', 'eleven token overrides', 'css'],
  ['largen.tokens.json', 'src/tokens.css', 'the token vocabulary as DTCG JSON', 'tokens'],
  ['theme-dark.tokens.json', 'themes/dark.css', 'the dark theme as a DTCG document', 'tokens'],
  ['site-example.css', 'sites/example/index.css', "a whole site: algebra + prose + theme + its own components", 'css'],
]

export async function build() {
  const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

  mkdirSync(join(root, 'dist'), { recursive: true })
  console.log('\n  largen build — concatenation and minification, not compilation\n')

  const files = {}
  let buildId = null

  for (const [out, entry, note, kind] of PROFILES) {
    /* The last profile bundles sites/example, which is a demonstration and is
       deliberately absent from the published package. Skipping a missing entry
       keeps `largen build` working from an install; failing on it would make a
       shipped command depend on a file the package does not ship. */
    if (!existsSync(join(root, entry))) {
      console.log(`  ${out.padEnd(24)} ${'skipped'.padStart(9)}             not in this package (${entry})`)
      continue
    }
    if (kind === 'tokens') {
      /* `themes/<name>.css` names the theme; src/tokens.css is the defaults and
         names none. Reading it off the path rather than off the output name
         keeps one fact in one place. */
      const themeName = entry.match(/^themes\/(.+)\.css$/)?.[1] ?? null
      const { tokens, colorScheme } = parseTokensCss(readFileSync(join(root, entry), 'utf8'))
      const doc = toDtcg(tokens, {
        version,
        build: buildId,
        theme: themeName,
        colorScheme,
        description:
          `largen ${version} ${themeName ? `${themeName} theme` : 'default'} tokens. ` +
          `Generated by \`largen build\` from ${entry}.`,
      })
      const code = JSON.stringify(doc, null, 2) + '\n'
      writeFileSync(join(root, 'dist', out), code)

      const buf = Buffer.from(code)
      files[out] = { bytes: buf.length, build: buildId, sha256: sha256(buf), integrity: sri(buf) }

      console.log(`  ${out.padEnd(24)} ${kb(code.length).padStart(9)} ${kb(gzipSync(code).length).padStart(9)} gz  ${buildId}`)
      console.log(`  ${''.padEnd(24)} ${note} — ${tokens.size} tokens, no banner`)
      continue
    }

    const body = bundle(join(root, entry))
    /* The entry point's body hash names the build. Deterministic: identical
       source gives an identical id, so a rebuild that changes nothing is
       visibly a no-op. */
    const id = sha256(body).slice(0, 8)
    if (out === 'largen.css') buildId = id

    const banner = `/*! largen ${version}+${id} | MIT | https://largen.dev */`
    const code = `${banner}\n${body}`
    writeFileSync(join(root, 'dist', out), code)

    const buf = Buffer.from(code)
    files[out] = { bytes: buf.length, build: id, sha256: sha256(buf), integrity: sri(buf) }

    console.log(`  ${out.padEnd(24)} ${kb(code.length).padStart(9)} ${kb(gzipSync(code).length).padStart(9)} gz  ${id}`)
    console.log(`  ${''.padEnd(24)} ${note}`)
  }

  const manifest = {
    $comment:
      'Generated by `largen build`. `sha256` and `integrity` are of the served ' +
      'bytes, banner included — these are what `curl | shasum -a 256` reproduces ' +
      'and what to record when vendoring. `build` is the hash of the bundle before ' +
      'the banner was added, which is what the banner itself prints; it names the ' +
      'build but is not the file digest. The .tokens.json documents carry no banner ' +
      "(a comment is not JSON) and their `build` is largen.css's id, naming the build " +
      'they were exported from; it is repeated inside each document, in ' +
      '$extensions["dev.largen"]. The unversioned paths are not immutable: ' +
      'pin by sha256, by integrity, or use a /v/<version>/ path.',
    version,
    build: buildId,
    files,
  }
  writeFileSync(join(root, 'dist', 'build.json'), JSON.stringify(manifest, null, 2) + '\n')
  console.log(`\n  build.json               ${buildId}  (sha256 + SRI for each file)\n`)
}
