/* Regenerate every surface that presents the authoring contract.
 *
 * site/mcp/contract.mjs is the source. SKILL.md, llms.txt and llms-compact.txt
 * are all downstream, and hand-editing any of them is a defect — the next run of
 * this command overwrites it. That is the whole point: the contract was
 * previously restated in three places and would have been in five.
 *
 * Note this reaches into site/, which is NOT part of the published package.
 * That is deliberate: this is a repository-development command, not something an
 * npm consumer runs. The error below says so rather than letting the import blow
 * up.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname } from 'node:path'
import { at } from './paths.mjs'

/* The hand-written SKILL.md was wrapped to about 80 columns, and that is worth
   keeping: it is a file people read in an editor and diff in a terminal. Prose
   goes through here; code blocks, tables and the model diagram must not. */
function wrap(text, width = 80, indent = '') {
  const out = []
  for (const para of String(text).split('\n')) {
    let line = indent
    for (const word of para.split(/\s+/).filter(Boolean)) {
      if (line.trim() && (line + ' ' + word).length > width) { out.push(line); line = indent + word }
      else line = line.trim() ? line + ' ' + word : indent + word
    }
    out.push(line)
  }
  return out.join('\n')
}

/* SKILL.md's frontmatter is metadata for the agent harness, not contract
   content, so it is preserved from the existing file rather than generated. */
function frontmatter() {
  const current = readFileSync(at('skill/SKILL.md'), 'utf8')
  const m = current.match(/^---\n[\s\S]*?\n---\n/)
  if (!m) throw new Error('skill/SKILL.md has no YAML frontmatter to preserve')
  return m[0]
}

function skillMarkdown(c) {
  const L = []
  L.push(frontmatter().trimEnd(), '')
  L.push('<!-- GENERATED by `largen contract` from site/mcp/contract.mjs. Do not edit. -->', '')
  L.push('# largen', '', wrap(c.overview.tagline), '')

  L.push('## The model', '', '```', c.overview.model, '```', '', wrap(c.overview.why), '')

  L.push('## Writing a component', '',
    '```css', c.overview.example.css, '```', '',
    '```html', c.overview.example.html, '```', '',
    wrap(c.overview.example.why), '')

  L.push('## The rules', '')
  c.rules.forEach((r, i) => L.push(wrap(`**${i + 1}. ${r.title}**`), wrap(r.why), ''))

  L.push('## The slots', '', wrap('`' + c.slots.fixed.join(' ') + '`'), '', wrap(c.slots.why), '',
    'Registered exactly as follows:', '', '```css', c.slots.registrations.join('\n'), '```', '',
    wrap('**Inheriting, registered:** ' +
      c.slots.inheriting.registered.map((s) => '`' + s + '`').join(', ') + '.'), '',
    wrap('**Inheriting, unregistered:** ' +
      c.slots.inheriting.ambient.map((s) => '`' + s + '`').join(', ') + '.'), '',
    wrap(c.slots.inheriting.why), '')

  L.push('## The paint rule', '', '```css', c.paint.rule, '```', '', wrap(c.paint.why), '')

  L.push('## The axes', '', '| axis | attribute | values | inherits |', '|---|---|---|---|')
  for (const [name, a] of Object.entries(c.axes)) {
    const attr = a.attribute ? '`' + a.attribute + '`' : '—'
    const vals = a.values.map((v) => (v.startsWith(':') ? '`' + v + '`' : v)).join(' ')
    const inh = a.inherits === null ? 'from the DOM' : a.inherits ? '**yes**' : 'no'
    L.push(`| ${name} | ${attr} | ${vals} | ${inh} |`)
  }
  L.push('')
  for (const [name, a] of Object.entries(c.axes)) L.push(wrap(`**${name}.** ${a.why}`), '')

  L.push('## When it goes wrong', '')
  for (const f of c.failureModes) {
    L.push(wrap(`**${f.symptom}**`), '', wrap(`Cause: ${f.cause}`) + '  ', wrap(`Fix: ${f.fix}`), '',
      wrap(f.why), '')
  }

  L.push('## Layout utilities', '')
  L.push(wrap(c.utilities.intro), '')
  const uw = Math.max(...c.utilities.list.map((u) => u.name.length))
  L.push('```')
  for (const u of c.utilities.list) L.push(`${u.name.padEnd(uw)}  ${u.does}`)
  L.push('```', '')
  L.push('| utility | reads |', '|---|---|')
  for (const u of c.utilities.list) L.push(`| \`${u.name}\` | \`${u.reads}\` |`)
  L.push('', wrap(c.utilities.alignment), '', wrap(c.utilities.why), '')

  L.push('## Composing a page', '')
  L.push(wrap('The rules above say what largen guarantees and how it fails. This is ' +
    'the other half. A page built to the rules alone comes out correct and plain.'), '')
  for (const part of Object.values(c.composition)) {
    L.push(wrap(`**${part.title}**`), '')
    for (const para of part.body.split('\n\n')) {
      L.push(para.startsWith('    ') ? para : wrap(para), '')
    }
  }

  L.push('## Commands', '', '```')
  const w = Math.max(...c.commands.list.map((x) => x.command.length))
  for (const x of c.commands.list) L.push(`${x.command.padEnd(w)}   # ${x.does}`)
  L.push('```', '', wrap(c.commands.caveat), '')

  L.push('## Layer order', '', '```', c.layers.order.join(' < '), '```', '', wrap(c.layers.why), '')
  /* Carried in full rather than pointed at. The measurement that justified the
     budget increase was of THIS material being present in the prompt: the same
     brief and model produced a page with rhythm, elevation and readable toned
     text when it was there, and none of those when it was not. A pointer would
     have reproduced the original result. */
  L.push('## Generative UI', '', wrap(c.generativeUI), '')
  for (const n of c.notes) L.push(wrap(`- ${n}`, 80, '') , '')
  return L.join('\n').replace(/\n{3,}/g, '\n\n') + '\n'
}

/* llms.txt — the index form of the convention: what this is, and where to go. */
function llmsTxt(c) {
  const L = []
  L.push('# largen', '', `> ${c.overview.tagline}`, '')
  L.push('largen is a property algebra rather than a component catalog. The library',
    `supplies ${c.slots.fixed.length} slots, four axes and one universal paint rule; each project`,
    'authors its own components on top of them. There is no build step.', '')
  L.push('## Start here', '')
  L.push('- [The whole contract, inline](https://largen.dev/llms-compact.txt): everything below in one file, sized for a prompt.')
  L.push('- [MCP server](https://largen.dev/docs/authoring): `claude mcp add largen --transport http https://largen.dev/api/mcp`')
  L.push('')
  L.push('## Documentation', '')
  L.push('- [The contract](https://largen.dev/docs/contract): slots, layers, and the rules for authoring a component.')
  L.push('- [The axes](https://largen.dev/docs/contract#the-axes): tone, variant, size and state.')
  L.push('- [Authoring](https://largen.dev/docs/authoring): writing a component, and how it fails.')
  L.push('- [Composing](https://largen.dev/llms-compact.txt): space, elevation, and what a slot cannot ' +
    'express. `get_contract` section "composition".')
  L.push('- [Components](https://largen.dev/docs/contract#reference-components): the optional reference set, to copy or ignore.')
  L.push('')
  L.push('## The one rule to know', '')
  L.push(wrap(c.rules[0].why), '')
  L.push('## Stylesheet', '')
  /* The CDN, not largen.dev. The stylesheets are distributed as an npm package
     and re-served by jsDelivr and unpkg, which makes a pinned version immutable
     because the registry refuses a second publish of one — a stronger guarantee
     than a path convention the site promises to honour. */
  L.push(`- Current: https://cdn.jsdelivr.net/npm/largen@latest/dist/largen.css`)
  L.push(`- Pinned:  https://cdn.jsdelivr.net/npm/largen@${c.version}/dist/largen.css (immutable)`)
  return L.join('\n') + '\n'
}

/* llms-compact.txt — the entire contract inline. A model that fetches this
   should need nothing else to author a correct component. */
function llmsCompact(c) {
  const L = []
  L.push(`# largen ${c.version}: the complete authoring contract`, '')
  L.push(c.overview.tagline, '')
  L.push(c.overview.model, '', wrap(c.overview.why), '')

  L.push('## Writing a component', '', c.overview.example.css, '',
    c.overview.example.html, '', wrap(c.overview.example.why), '')

  L.push('## Slots', '', wrap(c.slots.fixed.join(' ')), '', wrap(c.slots.why), '',
    c.slots.registrations.join('\n'), '',
    wrap('Inheriting, registered: ' + c.slots.inheriting.registered.join(' ')),
    wrap('Inheriting, unregistered: ' + c.slots.inheriting.ambient.join(' ')), '',
    wrap(c.slots.inheriting.why), '')

  L.push('## The paint rule', '', c.paint.rule, '', wrap(c.paint.why), '')

  L.push('## Axes', '')
  for (const [name, a] of Object.entries(c.axes)) {
    const attr = a.attribute ?? '(DOM state)'
    const inh = a.inherits === null ? 'from the DOM' : a.inherits ? 'inherits' : 'does not inherit'
    L.push(`${name}: ${attr}, ${inh}`, wrap(`values: ${a.values.join(' ')}`, 80, '  '),
      wrap(a.why, 80, '  '), '')
  }

  L.push('## Layer order', '', c.layers.order.join(' < '), '', wrap(c.layers.why), '')

  /* Authoring rules only.
   *
   * Same test as the failure-modes section below: this file's job is to be enough
   * to AUTHOR a component without fetching anything else. A rule that changes
   * which element you write belongs inline. A rule about where a project puts its
   * palette, or whether density is an axis, is architecture — you read it once
   * when setting the project up, not while writing a component, and carrying it
   * here pushed the file past its budget.
   *
   * Nothing is deleted: both are in SKILL.md, llms.txt, the docs site and
   * `get_contract` in full, all generated from the same source, and the pointer
   * below names them. The flag is opt-OUT for exactly one reason — a rule added
   * with no flag stays in this file, so the next one cannot be dropped by
   * forgetting something. */
  const inline = c.rules.filter((r) => r.compact !== false)
  const elsewhere = c.rules.filter((r) => r.compact === false)

  L.push('## Rules', '')
  if (elsewhere.length) {
    L.push(wrap('Project-architecture rules — ' +
      elsewhere.map((r) => `"${r.title.split('. ')[0]}"`).join(', ') +
      ' — are in `get_contract` section "rules" and at https://largen.dev/docs/contract.'), '')
  }
  inline.forEach((r, i) => L.push(`${i + 1}. ${r.title}`, wrap(r.why, 80, '   '), ''))

  /* Symptom and fix only.
   *
   * This file's job is to be enough to AUTHOR a component without fetching
   * anything else. Failure modes are diagnostic rather than instructional: you
   * reach for them when something has already gone wrong, and at that point you
   * can fetch the reasoning. Carrying every `why` inline pushed the file past its
   * own size budget, and it grew per failure mode — the eighth would have cost
   * another 800 characters to say something the seventh already implied.
   *
   * Symptom and fix are what let a model recognise and correct the problem. The
   * cause and the explanation live in get_contract, SKILL.md and the authoring
   * page, all generated from the same source, and the pointer below says so. */
  L.push('## How it fails', '')
  L.push(wrap('Symptom and fix. For why, fetch `get_contract` with section ' +
    '"failureModes", or read https://largen.dev/docs/authoring'), '')
  for (const f of c.failureModes) {
    L.push(wrap(`SYMPTOM  ${f.symptom}`), wrap(`FIX      ${f.fix}`), '')
  }

  /* Carried in full rather than pointed at. The measurement that justified the
     budget increase was of THIS material being in the prompt: the same brief and
     the same model produced rhythm, elevation and readable toned text when it was
     present, and none of them when it was not. A pointer would have reproduced
     the original result. */

  /* The utilities were seven words in the overview map and nothing anywhere else.
     A bake-off arm read that, used two of them, and hand-wrote `display: flex`
     ten more times with fifteen `align-items` beside it — every knob below was
     undocumented on every surface when that run happened. */
  L.push('## Layout utilities', '')
  L.push(wrap(c.utilities.intro), '')
  const uw = Math.max(...c.utilities.list.map((u) => u.name.length))
  const rw = Math.max(...c.utilities.list.map((u) => u.does.length))
  for (const u of c.utilities.list) {
    L.push(`${u.name.padEnd(uw)}  ${u.does.padEnd(rw)}  ${u.reads}`)
  }
  L.push('', wrap(c.utilities.alignment), '', wrap(c.utilities.why), '')

  L.push('## Composing a page', '')
  for (const part of Object.values(c.composition)) {
    L.push(wrap(part.title.toUpperCase()), '')
    for (const para of part.body.split('\n\n')) {
      L.push(para.startsWith('    ') ? para : wrap(para), '')
    }
  }

  L.push('## Generative UI', '', wrap(c.generativeUI), '')
  for (const n of c.notes) L.push(wrap(`- ${n}`), '')
  L.push('')
  L.push('## Commands', '')
  for (const x of c.commands.list) L.push(`${x.command}   # ${x.does}`)
  L.push('', wrap(c.commands.caveat))
  return L.join('\n').replace(/\n{3,}/g, '\n\n') + '\n'
}

const write = (rel, body) => {
  mkdirSync(dirname(at(rel)), { recursive: true })
  writeFileSync(at(rel), body)
  return body.length
}

export async function contract(args = []) {
  if (!existsSync(at('site/mcp/contract.mjs'))) {
    throw new Error(
      '`largen contract` needs site/, which is not part of the published package.\n' +
      '  Run it from a clone of the largen repository.')
  }
  const mod = await import('../../site/mcp/contract.mjs')
  mod.assertAxesAgree()
  const c = mod.buildContract()

  const check = args.includes('--check')
  const skill = skillMarkdown(c)
  const index = llmsTxt(c)
  const compact = llmsCompact(c)
  const { renderReleases } = await import('./releases.mjs')
  const releaseLog = renderReleases()

  /* ONE list, used by both the check and the write.
   *
   * Keeping two lists is what went wrong, three times. Writing four files and
   * comparing four files is fine until a fifth is added to one list and not the
   * other, and then --check reports "all generated surfaces are current" about a
   * set that no longer means all of them. It happened here to contract.html,
   * axes.html and authoring.html: this command writes them and the check never
   * opened them, so a nav change left a dead link in three pages and the check
   * said everything was fine.
   *
   * The comment that used to sit on the check said a partial check is worse than
   * no check because it is believed. It was right, and it was attached to a
   * partial check. Deriving both from one list is the only version of that
   * sentence a future edit cannot quietly falsify. */
  const surfaces = [
    ['skill/SKILL.md', skill],
    ['site/public/llms.txt', index],
    ['site/public/llms-compact.txt', compact],
    ['RELEASES.md', releaseLog],
  ]

  if (check) {
    const stale = surfaces.filter(([rel, want]) => {
      try { return readFileSync(at(rel), 'utf8') !== want } catch { return true }
    })
    if (stale.length) {
      throw new Error(`out of date — run \`largen contract\`:\n${stale.map(([f]) => `    ${f}`).join('\n')}`)
    }

    /* The hand-written pages have their own generator and the same problem: they
       are committed and served off disk, so nothing regenerates them and nothing
       compared them either. */
    const { pages: handWritten } = await import('./pages.mjs')
    await handWritten(['--check'])

    console.log(`  contract: ${surfaces.length} generated surface(s) are current\n`)
    return 0
  }

  for (const [rel, body] of surfaces) write(rel, body)
  const a = skill.length, b = index.length, d = compact.length

  const kb = (n) => (n / 1024).toFixed(2) + 'kb'
  console.log('\n  largen contract — generated from site/mcp/contract.mjs\n')
  console.log(`  skill/SKILL.md              ${kb(a).padStart(9)}`)
  console.log(`  site/public/llms.txt        ${kb(b).padStart(9)}`)
  console.log(`  site/public/llms-compact.txt${kb(d).padStart(9)}   ~${Math.ceil(d / 4)} tokens`)

  /* The compact file is meant to fit comfortably in a prompt. If it stops
     fitting, that is evidence the contract has outgrown what the design claims,
     and the spec says to report it rather than quietly accept it. */
  /* Raised from 16kb, deliberately and with evidence rather than because it was
     in the way.
   *
     A bake-off ran one brief through one model on largen and on Tailwind. The
     largen page passed every check and looked plain. Adding composition guidance
     to the prompt — and changing nothing else — produced rhythm, elevation, a
     working gradient and readable text on toned surfaces. That material is ~4kb
     and there were 463 bytes of headroom, so the old budget could not carry the
     thing that demonstrably improved the output.
   *
     The check and this warning stay. The number moved; the discipline did not.
     24kb is roughly 6,000 tokens, about 3% of a 200k context window — still small
     enough that inlining it costs a caller little, which is the property the
     budget exists to protect. */
  const LIMIT = 24 * 1024
  if (d > LIMIT) {
    console.log(`\n  WARNING: llms-compact.txt is ${kb(d)}, over the ${kb(LIMIT)} budget.`)
    console.log('  The contract has grown beyond "small enough to inline". Trim it or')
    console.log('  split it deliberately — do not just raise the limit.')
  }
  console.log()
  return 0
}
