/* Regenerate every surface that presents the authoring contract.
 *
 * site/mcp/contract.mjs is the source. SKILL.md, llms.txt and llms-compact.txt
 * are all downstream, and hand-editing any of them is a defect — the next run of
 * this command overwrites it. That is the whole point: the contract was
 * previously restated in three places and would have been in five.
 *
 * Note this reaches into site/, which is NOT part of the published package.
 * That is deliberate: this is a repository-development command, not something an
 * npm consumer runs. The error below says so rather than letting the import blow
 * up.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname } from 'node:path'
import { at } from './paths.mjs'

/* The hand-written SKILL.md was wrapped to about 80 columns, and that is worth
   keeping: it is a file people read in an editor and diff in a terminal. Prose
   goes through here; code blocks, tables and the model diagram must not. */
function wrap(text, width = 80, indent = '') {
  const out = []
  for (const para of String(text).split('\n')) {
    let line = indent
    for (const word of para.split(/\s+/).filter(Boolean)) {
      if (line.trim() && (line + ' ' + word).length > width) { out.push(line); line = indent + word }
      else line = line.trim() ? line + ' ' + word : indent + word
    }
    out.push(line)
  }
  return out.join('\n')
}

/* SKILL.md's frontmatter is metadata for the agent harness, not contract
   content, so it is preserved from the existing file rather than generated. */
function frontmatter() {
  const current = readFileSync(at('skill/SKILL.md'), 'utf8')
  const m = current.match(/^---\n[\s\S]*?\n---\n/)
  if (!m) throw new Error('skill/SKILL.md has no YAML frontmatter to preserve')
  return m[0]
}

function skillMarkdown(c) {
  const L = []
  L.push(frontmatter().trimEnd(), '')
  L.push('<!-- GENERATED by `largen contract` from site/mcp/contract.mjs. Do not edit. -->', '')
  L.push('# largen', '', wrap(c.overview.tagline), '')

  L.push('## The model', '', '```', c.overview.model, '```', '', wrap(c.overview.why), '')

  L.push('## Writing a component', '',
    '```css', c.overview.example.css, '```', '',
    '```html', c.overview.example.html, '```', '',
    wrap(c.overview.example.why), '')

  L.push('## The rules', '')
  c.rules.forEach((r, i) => L.push(wrap(`**${i + 1}. ${r.title}**`), wrap(r.why), ''))

  L.push('## The paint rule', '', '```css', c.paint.rule, '```', '', wrap(c.paint.why), '')

  L.push('## The slots', '', wrap('`' + c.slots.fixed.join(' ') + '`'), '', wrap(c.slots.why), '',
    'Registered exactly as follows:', '', '```css', c.slots.registrations.join('\n'), '```', '',
    wrap('**Inheriting, registered:** ' +
      c.slots.inheriting.registered.map((s) => '`' + s + '`').join(', ') + '.'), '',
    wrap('**Inheriting, unregistered:** ' +
      c.slots.inheriting.ambient.map((s) => '`' + s + '`').join(', ') + '.'), '',
    wrap(c.slots.inheriting.why), '')

  L.push('## The axes', '', '| axis | attribute | values | inherits |', '|---|---|---|---|')
  for (const [name, a] of Object.entries(c.axes)) {
    const attr = a.attribute ? '`' + a.attribute + '`' : '—'
    const vals = a.values.map((v) => (v.startsWith(':') ? '`' + v + '`' : v)).join(' ')
    const inh = a.inherits === null ? 'from the DOM' : a.inherits ? '**yes**' : 'no'
    L.push(`| ${name} | ${attr} | ${vals} | ${inh} |`)
  }
  L.push('')
  for (const [name, a] of Object.entries(c.axes)) L.push(wrap(`**${name}** — ${a.why}`), '')

  L.push('## When it goes wrong', '')
  for (const f of c.failureModes) {
    L.push(wrap(`**${f.symptom}**`), '', wrap(`Cause: ${f.cause}`) + '  ', wrap(`Fix: ${f.fix}`), '',
      wrap(f.why), '')
  }

  L.push('## Commands', '', '```')
  const w = Math.max(...c.commands.list.map((x) => x.command.length))
  for (const x of c.commands.list) L.push(`${x.command.padEnd(w)}   # ${x.does}`)
  L.push('```', '', wrap(c.commands.caveat), '')

  L.push('## Layer order', '', '```', c.layers.order.join(' < '), '```', '', wrap(c.layers.why), '')
  L.push('## Generative UI', '', wrap(c.generativeUI), '')
  for (const n of c.notes) L.push(wrap(`- ${n}`, 80, '') , '')
  return L.join('\n').replace(/\n{3,}/g, '\n\n') + '\n'
}

/* llms.txt — the index form of the convention: what this is, and where to go. */
function llmsTxt(c) {
  const L = []
  L.push('# largen', '', `> ${c.overview.tagline}`, '')
  L.push('largen is a property algebra rather than a component catalog. The library',
    `supplies ${c.slots.fixed.length} slots, four axes and one universal paint rule; each project`,
    'authors its own components on top of them. There is no build step.', '')
  L.push('## Start here', '')
  L.push('- [The whole contract, inline](https://largen.dev/llms-compact.txt): everything below in one file, sized for a prompt.')
  L.push('- [MCP server](https://largen.dev/docs/mcp.html): `claude mcp add largen --transport http https://largen.dev/api/mcp`')
  L.push('')
  L.push('## Documentation', '')
  L.push('- [The contract](https://largen.dev/docs/contract.html): slots, layers, and the rules for authoring a component.')
  L.push('- [The axes](https://largen.dev/docs/axes.html): tone, variant, size and state.')
  L.push('- [Authoring](https://largen.dev/docs/authoring.html): writing a component, and how it fails.')
  L.push('- [Components](https://largen.dev/docs/components.html): the optional reference set, to copy or ignore.')
  L.push('')
  L.push('## The one rule to know', '')
  L.push(wrap(c.rules[0].why), '')
  L.push('## Stylesheet', '')
  L.push(`- Current: https://largen.dev/largen.css`)
  L.push(`- Pinned:  https://largen.dev/v/${c.version}/largen.css (immutable)`)
  return L.join('\n') + '\n'
}

/* llms-compact.txt — the entire contract inline. A model that fetches this
   should need nothing else to author a correct component. */
function llmsCompact(c) {
  const L = []
  L.push(`# largen ${c.version} — the complete authoring contract`, '')
  L.push(c.overview.tagline, '')
  L.push(c.overview.model, '', wrap(c.overview.why), '')

  L.push('## Writing a component', '', c.overview.example.css, '',
    c.overview.example.html, '', wrap(c.overview.example.why), '')

  L.push('## The paint rule', '', c.paint.rule, '', wrap(c.paint.why), '')

  L.push('## Slots', '', wrap(c.slots.fixed.join(' ')), '', wrap(c.slots.why), '',
    c.slots.registrations.join('\n'), '',
    wrap('Inheriting, registered: ' + c.slots.inheriting.registered.join(' ')),
    wrap('Inheriting, unregistered: ' + c.slots.inheriting.ambient.join(' ')), '',
    wrap(c.slots.inheriting.why), '')

  L.push('## Axes', '')
  for (const [name, a] of Object.entries(c.axes)) {
    const attr = a.attribute ?? '(DOM state)'
    const inh = a.inherits === null ? 'from the DOM' : a.inherits ? 'inherits' : 'does not inherit'
    L.push(`${name} — ${attr} — ${inh}`, wrap(`values: ${a.values.join(' ')}`, 80, '  '),
      wrap(a.why, 80, '  '), '')
  }

  L.push('## Layer order', '', c.layers.order.join(' < '), '', wrap(c.layers.why), '')

  L.push('## Rules', '')
  c.rules.forEach((r, i) => L.push(`${i + 1}. ${r.title}`, wrap(r.why, 80, '   '), ''))

  /* Symptom and fix only.
   *
   * This file's job is to be enough to AUTHOR a component without fetching
   * anything else. Failure modes are diagnostic rather than instructional: you
   * reach for them when something has already gone wrong, and at that point you
   * can fetch the reasoning. Carrying every `why` inline pushed the file past its
   * own size budget, and it grew per failure mode — the eighth would have cost
   * another 800 characters to say something the seventh already implied.
   *
   * Symptom and fix are what let a model recognise and correct the problem. The
   * cause and the explanation live in get_contract, SKILL.md and the authoring
   * page, all generated from the same source, and the pointer below says so. */
  L.push('## How it fails', '')
  L.push(wrap('Symptom and fix. For why, fetch `get_contract` with section ' +
    '"failureModes", or read https://largen.dev/docs/authoring.html'), '')
  for (const f of c.failureModes) {
    L.push(wrap(`SYMPTOM  ${f.symptom}`), wrap(`FIX      ${f.fix}`), '')
  }

  L.push('## Generative UI', '', wrap(c.generativeUI), '')
  for (const n of c.notes) L.push(wrap(`- ${n}`), '')
  L.push('')
  L.push('## Commands', '')
  for (const x of c.commands.list) L.push(`${x.command} — ${x.does}`)
  L.push('', wrap(c.commands.caveat))
  return L.join('\n').replace(/\n{3,}/g, '\n\n') + '\n'
}

const write = (rel, body) => {
  mkdirSync(dirname(at(rel)), { recursive: true })
  writeFileSync(at(rel), body)
  return body.length
}

/* --- The contract-derived documentation pages ----------------------------
 *
 * contract.html, axes.html and authoring.html present the contract, so the
 * authoring-contract spec requires them to be generated from it rather than
 * hand-maintained alongside it. The other pages are hand-written: they are
 * about the project, not the contract, and nothing generates them.
 *
 * This is still a build-free site. The output is static HTML committed to the
 * repository and served straight off disk — regenerating it is the same kind of
 * optional dev-time command as `largen build`, not a step between a request and
 * a response.
 */

function contractPages(c, page, inline, esc) {
  const specRow = (name, note) =>
    `  <div class="spec-row"><span class="spec-name">${esc(name)}</span>` +
    `<span class="spec-note">${note ? inline(note) : ''}</span></div>`

  const contractBody = [
    '<div class="stack" style="--gap:.4rem">',
    '  <h1 class="page-title">The contract</h1>',
    `  <p class="page-desc">${c.slots.fixed.length} slots, one universal paint rule, and one rule about`,
    '  layers that explains most of what goes wrong.</p>',
    '</div>',
    '',
    '<section class="stack" style="--gap:.75rem">',
    '  <h2 class="section-title">The model</h2>',
    `  <pre class="code">${esc(c.overview.model)}</pre>`,
    `  <p class="spec-note">${inline(c.overview.why)}</p>`,
    '</section>',
    '',
    '<section class="stack" style="--gap:.75rem">',
    '  <h2 class="section-title">The paint rule</h2>',
    `  <pre class="code">${esc(c.paint.rule)}</pre>`,
    `  <p class="spec-note">${inline(c.paint.why)}</p>`,
    '</section>',
    '',
    '<section class="stack" style="--gap:.5rem">',
    '  <h2 class="section-title">The slots</h2>',
    `  <p class="spec-note">${inline(c.slots.why)}</p>`,
    '  <div class="stack" style="--gap:0">',
    ...c.slots.fixed.map((s) => specRow(s, 'registered `inherits: false`, no `initial-value`')),
    '  </div>',
    `  <pre class="code">${esc(c.slots.registrations.join('\n'))}</pre>`,
    '</section>',
    '',
    '<section class="stack" style="--gap:.5rem">',
    '  <h2 class="section-title">What inherits, and how</h2>',
    `  <p class="spec-note">${inline(c.slots.inheriting.why)}</p>`,
    '  <div class="stack" style="--gap:0">',
    ...c.slots.inheriting.registered.map((s) => specRow(s, 'registered `inherits: true` — type-checked, animatable')),
    ...c.slots.inheriting.ambient.map((s) => specRow(s, 'not registered — inherits because that is the default')),
    '  </div>',
    '</section>',
    '',
    '<section class="stack" style="--gap:.5rem">',
    '  <h2 class="section-title">Layer order</h2>',
    `  <pre class="code">${esc(c.layers.order.join('\n  < '))}</pre>`,
    `  <p class="spec-note">${inline(c.layers.why)}</p>`,
    '</section>',
  ].join('\n')

  const axesBody = [
    '<div class="stack" style="--gap:.4rem">',
    '  <h1 class="page-title">The axes</h1>',
    '  <p class="page-desc">Four axes. A component mentions none of them and gets all',
    '  of them.</p>',
    '</div>',
    ...Object.entries(c.axes).flatMap(([name, a]) => [
      '',
      '<section class="stack" style="--gap:.6rem">',
      `  <h2 class="section-title">${esc(name)}</h2>`,
      '  <div class="stack" style="--gap:0">',
      specRow('attribute', a.attribute ? '`' + a.attribute + '`' : 'none — it comes from the DOM'),
      specRow('inherits', a.inherits === null ? 'from the DOM' : a.inherits ? 'yes' : 'no'),
      specRow('values', a.values.map((v) => '`' + v + '`').join(' · ')),
      '  </div>',
      `  <p class="spec-note">${inline(a.why)}</p>`,
      '</section>',
    ]),
  ].join('\n')

  const authoringBody = [
    '<div class="stack" style="--gap:.4rem">',
    '  <h1 class="page-title">Authoring a component</h1>',
    '  <p class="page-desc">Six rules, and the four ways it goes wrong when you break',
    '  them.</p>',
    '</div>',
    '',
    '<section class="stack" style="--gap:.75rem">',
    '  <h2 class="section-title">A complete component</h2>',
    `  <pre class="code">${esc(c.overview.example.css)}</pre>`,
    `  <pre class="code">${esc(c.overview.example.html)}</pre>`,
    `  <p class="spec-note">${inline(c.overview.example.why)}</p>`,
    '</section>',
    '',
    '<section class="stack" style="--gap:.75rem">',
    '  <h2 class="section-title">The rules</h2>',
    ...c.rules.map((r, i) => [
      '  <div class="rule">',
      `    <span class="rule-title">${i + 1}. ${inline(r.title)}</span>`,
      `    <p class="rule-why">${inline(r.why)}</p>`,
      '  </div>',
    ].join('\n')),
    '</section>',
    '',
    '<section class="stack" style="--gap:.75rem">',
    '  <h2 class="section-title">When it goes wrong</h2>',
    '  <p class="spec-note">The first one is the one to memorise. It is the only failure',
    '  in largen that looks like success.</p>',
    ...c.failureModes.map((f, i) => [
      `  <div class="failure" data-tone="${i === 0 ? 'danger' : 'warning'}">`,
      `    <span class="failure-symptom">${inline(f.symptom)}</span>`,
      `    <span class="failure-line"><strong>Cause</strong> — ${inline(f.cause)}</span>`,
      `    <span class="failure-line"><strong>Fix</strong> — ${inline(f.fix)}</span>`,
      `    <p class="failure-line">${inline(f.why)}</p>`,
      '  </div>',
    ].join('\n')),
    '</section>',
    '',
    '<section class="stack" style="--gap:.5rem">',
    '  <h2 class="section-title">Check what you wrote</h2>',
    '  <p class="spec-note">Locally, <span class="tok">npx largen verify</span>. Over MCP,',
    '  <span class="tok">check_component_css</span>. Both run the same rules from the same',
    '  module, so they cannot disagree.</p>',
    '  <p class="spec-note">Both are static. They have passed clean on visibly broken',
    '  components before — render the result in a browser, in both themes.</p>',
    '</section>',
  ].join('\n')

  const v = c.version
  return {
    'site/public/docs/contract.html': page({
      title: 'The contract — largen', current: 'contract', version: v,
      description: `largen's ${c.slots.fixed.length} slots, the layer rule, and the universal paint rule.`,
      body: contractBody }),
    'site/public/docs/axes.html': page({
      title: 'The axes — largen', current: 'axes', version: v,
      description: 'tone, variant, size and state — the four axes a largen component gets for free.',
      body: axesBody }),
    'site/public/docs/authoring.html': page({
      title: 'Authoring — largen', current: 'authoring', version: v,
      description: 'How to write a largen component, and the four ways it goes wrong.',
      body: authoringBody }),
  }
}

export async function contract(args = []) {
  if (!existsSync(at('site/mcp/contract.mjs'))) {
    throw new Error(
      '`largen contract` needs site/, which is not part of the published package.\n' +
      '  Run it from a clone of the largen repository.')
  }
  const mod = await import('../../site/mcp/contract.mjs')
  mod.assertAxesAgree()
  const c = mod.buildContract()

  const check = args.includes('--check')
  const skill = skillMarkdown(c)
  const index = llmsTxt(c)
  const compact = llmsCompact(c)

  if (check) {
    const current = readFileSync(at('skill/SKILL.md'), 'utf8')
    if (current !== skill) {
      throw new Error('skill/SKILL.md is out of date — run `largen contract`')
    }
    console.log('\n  contract: all generated surfaces are current\n')
    return 0
  }

  const a = write('skill/SKILL.md', skill)
  const b = write('site/public/llms.txt', index)
  const d = write('site/public/llms-compact.txt', compact)

  const { page, inline, esc } = await import('../../site/mcp/page.mjs')
  const pages = contractPages(c, page, inline, esc)
  for (const [path, html] of Object.entries(pages)) write(path, html)

  const kb = (n) => (n / 1024).toFixed(2) + 'kb'
  console.log('\n  largen contract — generated from site/mcp/contract.mjs\n')
  console.log(`  skill/SKILL.md              ${kb(a).padStart(9)}`)
  console.log(`  site/public/llms.txt        ${kb(b).padStart(9)}`)
  console.log(`  site/public/llms-compact.txt${kb(d).padStart(9)}   ~${Math.ceil(d / 4)} tokens`)
  for (const path of Object.keys(pages)) console.log(`  ${path}`)

  /* The compact file is meant to fit comfortably in a prompt. If it stops
     fitting, that is evidence the contract has outgrown what the design claims,
     and the spec says to report it rather than quietly accept it. */
  const LIMIT = 16 * 1024
  if (d > LIMIT) {
    console.log(`\n  WARNING: llms-compact.txt is ${kb(d)}, over the ${kb(LIMIT)} budget.`)
    console.log('  The contract has grown beyond "small enough to inline". Trim it or')
    console.log('  split it deliberately — do not just raise the limit.')
  }
  console.log()
  return 0
}
