/* Regenerate the generative-UI artifacts from genai/manifest.json.
 * schema.json, prompt.md and manifest.js are all downstream; hand-editing any of
 * them is a bug, which is what this exists to prevent. */
import { readFileSync, writeFileSync } from 'node:fs'
import { at } from './paths.mjs'

export async function gen() {
  const manifest = JSON.parse(readFileSync(at('genai/manifest.json'), 'utf8'))

  writeFileSync(at('genai/manifest.js'),
    `// GENERATED by \`largen gen\` from manifest.json. Do not edit.\n` +
    `export default ${JSON.stringify(manifest, null, 2)}\n`)

  const names = manifest.components.map((c) => c.name)
  const schema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://largen.css/genai/schema.json',
    title: 'largen node',
    description: 'One approved component. The model chooses a component and a tone; ' +
      'it cannot express a colour, a class or inline CSS.',
    type: 'object', additionalProperties: false, required: ['component'],
    properties: {
      component: { type: 'string', enum: names, description: 'Which approved component to render.' },
      tone: { type: 'string', enum: manifest.axes.tone.values, description: manifest.axes.tone.description },
      variant: { type: 'string', enum: manifest.axes.variant.values, description: manifest.axes.variant.description },
      size: { type: 'string', enum: manifest.axes.size.values, description: manifest.axes.size.description },
      text: { type: 'string', description: 'Plain text content. Never markup.' },
      children: { type: 'array', items: { $ref: '#' } },
    },
  }
  writeFileSync(at('genai/schema.json'), JSON.stringify(schema, null, 2) + '\n')

  const L = [
    '<!-- GENERATED by `largen gen` from manifest.json. Do not edit. -->',
    '# Approved UI components', '',
    'Render UI by naming a component from this list. Never emit HTML, CSS, class',
    'names or colours — choose a `component`, and optionally a `tone`, `variant`',
    'and `size`. Anything outside these lists is rejected before it reaches the page.',
    '',
  ]
  for (const [k, a] of Object.entries(manifest.axes)) {
    L.push(`**${k}** — ${a.description}`, '', '`' + a.values.join('` · `') + '`', '')
  }
  L.push('## Components', '')
  for (const c of manifest.components) L.push(`- \`${c.name}\` — ${c.for}`)
  L.push('', '## Notes', '')
  for (const n of manifest.notes) L.push(`- ${n}`)
  writeFileSync(at('genai/prompt.md'), L.join('\n') + '\n')

  console.log(`\n  genai: ${names.length} components -> manifest.js, schema.json, prompt.md\n`)
}
