/* Derive a component manifest from a project's CSS.
 *
 * The MCP server cannot know what components a project has — that is largen's
 * whole premise — so the calling agent generates this and passes it in. The
 * server is then a pure function over supplied input rather than a catalog with
 * an opinion about somebody else's stylesheet.
 *
 * Output is shaped like genai/manifest.json on purpose: the same file that feeds
 * genai/validate.js locally is the one the server accepts, so a spec that
 * validates in the project validates over MCP.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { at } from './paths.mjs'
import { detectComponents } from './detect.mjs'

export async function manifest(args = []) {
  const out = (() => {
    const i = args.indexOf('--out')
    return i >= 0 ? args[i + 1] : null
  })()
  const files = args.filter((a, i) => !a.startsWith('--') && args[i - 1] !== '--out')

  if (!files.length) {
    throw new Error(
      'usage: largen manifest <css...> [--out manifest.json]\n' +
      '  e.g. largen manifest src/components.css --out largen.manifest.json')
  }

  const { readSlots } = await import('../../site/mcp/contract.mjs')
  const slots = readSlots().fixed
  const base = JSON.parse(readFileSync(at('genai/manifest.json'), 'utf8'))

  const all = new Map()
  const skippedTotals = []
  for (const f of files) {
    const css = readFileSync(f, 'utf8')
    const { components, skipped } = detectComponents(css, slots)
    skippedTotals.push([f, components.length, skipped.length])
    for (const c of components) {
      const prev = all.get(c.name)
      if (prev) {
        prev.slots = [...new Set([...prev.slots, ...c.slots])].sort()
        prev.description ??= c.description
      } else all.set(c.name, { ...c, source: f })
    }
  }

  const components = [...all.values()].sort((a, b) => a.name.localeCompare(b.name))
  const doc = {
    $comment:
      `Generated by \`largen manifest\` from ${files.join(', ')}. ` +
      'Pass this to the largen MCP server so its tools answer in terms of this ' +
      "project's components rather than largen's reference set.",
    version: base.version,
    axes: base.axes,
    notes: base.notes,
    components: components.map((c) => ({
      name: c.name,
      for: c.description ?? undefined,
      element: c.element,
      slots: c.slots,
    })),
  }

  const json = JSON.stringify(doc, null, 2) + '\n'
  if (out) writeFileSync(out, json)
  else process.stdout.write(json)

  const undescribed = components.filter((c) => !c.description)
  const log = out ? console.log : console.error   /* keep stdout pure when piping */

  log('')
  for (const [f, n, s] of skippedTotals) log(`  ${f} — ${n} components, ${s} rules skipped`)
  log(`\n  ${components.length} components${out ? ` -> ${out}` : ''}`)

  /* An undescribed component is harder for a model to use correctly, so the
     omission is reported rather than passed over. It is not an error: the
     stylesheet is still the source of truth for what exists. */
  if (undescribed.length) {
    log(`\n  ${undescribed.length} of ${components.length} have no description.`)
    log('  Add one with an annotation immediately above the rule:\n')
    log('      /** @largen Shows a single figure with a label. */')
    log(`      .${undescribed[0].name} { … }\n`)
    log('  ' + undescribed.map((c) => c.name).join(' '))
  }
  log('')
  return 0
}
