/* `largen releases` — the release log, and the check that it is true.
 *
 * A changelog is the one document in a repository that nothing verifies. It is
 * written at the moment of least certainty, from memory, about work that is
 * already finished, and it is read by people deciding whether an upgrade will
 * break them. When it is wrong it is wrong in the direction that costs most.
 *
 * largen freezes every release at an immutable path under site/public/v/, which
 * means the bytes each version actually shipped are still on disk. So the log can
 * be checked rather than trusted: each entry carries `signals` — strings that must
 * be PRESENT in that version's frozen largen.css and strings that must be ABSENT.
 * "0.3.0 adds --line-height" is then a claim with a witness.
 *
 * The signals do a second job. A per-project upgrade check needs to know what
 * changed between the version a project vendored and the current one, in a form
 * it can grep for. That is exactly this list, which is why it is data here rather
 * than sentences in a markdown file.
 */
import { readFileSync, existsSync, writeFileSync, readdirSync } from 'node:fs'
import { at } from './paths.mjs'

const load = () => JSON.parse(readFileSync(at('genai/releases.json'), 'utf8')).releases

const bullet = (item) => (typeof item === 'string' ? item : item.change)
const detail = (item) => (typeof item === 'string' ? null : item)

/** The log as markdown. Generated, never hand-edited. */
export function renderReleases(releases = load()) {
  const out = [
    '# Releases',
    '',
    'Generated from `genai/releases.json` by `largen contract`. Do not edit this file.',
    '',
    'Every entry is checked against the bytes that version actually shipped, frozen at',
    '`/v/<version>/`. Run `largen releases --check`.',
    '',
    'Versioned paths are immutable. The unversioned `/largen.css` is not — it tracks the',
    'newest build, so pin by version, by `sha256`, or by the `integrity` string in',
    '`build.json` if you need bytes that cannot change under you.',
    '',
  ]

  for (const r of releases) {
    out.push(`## ${r.version} — ${r.date}`, '', r.summary, '')

    if (r.breaking.length) {
      out.push('### Breaking', '')
      for (const b of r.breaking) {
        const d = detail(b)
        out.push(`- **${bullet(b)}**`)
        if (d?.why) out.push(`  ${d.why}`)
        if (d?.migration) out.push(`  *To migrate:* ${d.migration}`)
      }
      out.push('')
    }

    for (const [key, heading] of [['added', 'Added'], ['fixed', 'Fixed'], ['tooling', 'Tooling']]) {
      const items = r[key] ?? []
      if (!items.length) continue
      out.push(`### ${heading}`, '')
      for (const item of items) {
        const d = detail(item)
        out.push(`- ${bullet(item)}`)
        if (d?.why) out.push(`  ${d.why}`)
      }
      out.push('')
    }
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n') + '\n'
}

/** Check every entry against the frozen artifact for that version. */
export function checkReleases(releases = load()) {
  const findings = []
  const checked = []

  for (const r of releases) {
    const frozen = at('site/public/v', r.version, 'largen.css')
    if (!existsSync(frozen)) {
      /* Not a failure on its own — the newest entry is written before the freeze.
         It becomes one the moment that version is published. */
      findings.push({ version: r.version, severity: 'pending', message: `not frozen yet at /v/${r.version}/largen.css` })
      continue
    }
    const css = readFileSync(frozen, 'utf8')
    const { present = [], absent = [] } = r.signals ?? {}
    for (const s of present) {
      if (!css.includes(s)) {
        findings.push({ version: r.version, severity: 'error', message: `claims \`${s}\` but the frozen build does not contain it` })
      }
    }
    for (const s of absent) {
      if (css.includes(s)) {
        findings.push({ version: r.version, severity: 'error', message: `claims \`${s}\` is gone, but the frozen build still contains it` })
      }
    }
    checked.push({ version: r.version, signals: present.length + absent.length })
  }

  /* An entry per published version, and no published version without an entry.
     A release nobody wrote down is the failure this whole file is about. */
  const named = new Set(releases.map((r) => r.version))
  const dir = at('site/public/v')
  if (existsSync(dir)) {
    const published = readdirSync(dir).filter((f) => /^\d+\.\d+\.\d+$/.test(f))
    for (const v of published) {
      if (!named.has(v)) findings.push({ version: v, severity: 'error', message: 'is published but has no entry in the log' })
    }
  }

  /* dist/ is what npm ships; site/public/v/<version>/ is what the site pins. They
     are produced by the same build and must not diverge, but nothing forced that
     until now: editing src/, rebuilding, and publishing would put different bytes
     on the registry than at the pinned path — under a version whose whole promise
     is that its bytes never change. Two distribution channels make this a real
     hazard rather than a theoretical one.

     Only checked when dist/ exists. It is gitignored and built on demand, so a
     fresh clone has none and that is not a failure. */
  const current = JSON.parse(readFileSync(at('package.json'), 'utf8')).version
  const frozenDir = at('site/public/v', current)
  if (existsSync(at('dist')) && existsSync(frozenDir)) {
    for (const f of readdirSync(at('dist')).filter((x) => x.endsWith('.css'))) {
      const pinned = at('site/public/v', current, f)
      if (!existsSync(pinned)) continue
      if (!readFileSync(at('dist', f)).equals(readFileSync(pinned))) {
        findings.push({
          version: current,
          severity: 'error',
          message: `dist/${f} differs from the frozen /v/${current}/${f}. npm would ship ` +
            'different bytes than the pinned path, under a version that promises it will not. ' +
            'Bump the version, or re-freeze with `largen release --force` if nothing has ' +
            'consumed it yet.',
        })
      }
    }
  }

  return { ok: !findings.some((f) => f.severity === 'error'), findings, checked }
}

export async function releases(args = []) {
  const write = args.includes('--write')
  const check = args.includes('--check')
  const list = load()

  if (write) {
    writeFileSync(at('RELEASES.md'), renderReleases(list))
    console.log(`\n  wrote RELEASES.md — ${list.length} release(s)\n`)
    return 0
  }

  if (check) {
    const r = checkReleases(list)
    console.log()
    for (const c of r.checked) console.log(`  ok    ${c.version} — ${c.signals} signal(s) match the frozen build`)
    for (const f of r.findings) {
      console.log(`  ${f.severity === 'error' ? 'FAIL' : 'note'}  ${f.version} ${f.message}`)
    }
    const current = JSON.parse(readFileSync(at('package.json'), 'utf8')).version
    if (list[0].version !== current) {
      console.log(`  FAIL  package.json is ${current} but the newest entry is ${list[0].version}`)
      return 1
    }
    console.log(`\n  ${r.ok ? 'the release log matches what was published' : 'the release log disagrees with what was published'}\n`)
    return r.ok ? 0 : 1
  }

  console.log(renderReleases(list))
  return 0
}

export default releases
