/* `largen tokens` — a project's stylesheet in, a DTCG token document out.
 *
 * The export direction, and the mirror of `largen theme`. Together they are a
 * round trip: take a theme into Figma, Tokens Studio or Style Dictionary, edit
 * it there, bring it back as CSS.
 *
 * It exists because the export was reachable only through the module. `largen
 * build` exports largen's own two stylesheets and takes no arguments, so the
 * one caller who most needs the parser — somebody pointing it at a theme a
 * person wrote by hand — had nothing to run and no diagnostics to read.
 *
 * The reading is the point, and it is not a given. A stylesheet declares its
 * tokens in one rule among many, and the rules around it — `@font-face`,
 * `@media`, an `html { … }` reset — are not that rule. What the parser could
 * not read, or read with a guess, comes back as a warning rather than as a
 * smaller document, because a document that is quietly short is worse than one
 * that says what it missed.
 *
 * Human output goes to stderr and the document to stdout, without exception,
 * so `largen tokens theme.css > theme.tokens.json` writes JSON and nothing
 * else even when the parse warns.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { at } from './paths.mjs'
import { parseTokensCss, toDtcg } from '../../genai/tokens.js'

const USAGE = `
  largen tokens — derive a DTCG token document from a project's stylesheet

    largen tokens themes/brand.css
    largen tokens themes/brand.css --out brand.tokens.json
    largen tokens themes/dark.css --theme dark > dark.tokens.json

  Options
    --out FILE      write here instead of stdout
    --theme NAME    the theme name recorded in the document; overrides the one
                    read off the rule's [data-theme="…"] selector

  It reads the first rule that declares custom properties — inside
  \`@layer largen.tokens\` when the sheet is layered — and maps what it finds
  onto largen's token vocabulary. A property the vocabulary does not name is
  kept as a project extra, so nothing in the sheet is dropped.

  Warnings say what could not be read: a sheet that declares no custom
  properties at all, a second rule that declares some and was not read, a
  declaring rule that sits inside a conditional at-rule. A sheet with no tokens
  writes nothing and exits 1, because an empty document is never the answer.

  \`largen theme\` reads what this writes.
`

export async function tokens(args = []) {
  if (args.includes('--help') || args.includes('-h')) { console.error(USAGE); return 0 }

  const flag = (name) => {
    const i = args.indexOf(name)
    return i >= 0 ? args[i + 1] : null
  }
  const out = flag('--out')
  const theme = flag('--theme')
  const files = args.filter(
    (a, i) => !a.startsWith('--') && args[i - 1] !== '--out' && args[i - 1] !== '--theme')

  if (files.length !== 1) {
    throw new Error(
      'usage: largen tokens <file.css> [--out FILE] [--theme NAME]\n' +
      '  e.g. largen tokens themes/brand.css --out brand.tokens.json')
  }
  const file = files[0]
  if (!existsSync(file)) { console.error(`\n  no such file: ${file}\n`); return 1 }

  const parsed = parseTokensCss(readFileSync(file, 'utf8'))
  const { selector, colorScheme, tokens: map } = parsed
  const warnings = parsed.warnings ?? []

  /* No path on these, unlike the import diagnostics: they are about a rule in a
     stylesheet, and there is no token path to name yet. */
  if (warnings.length) console.error('')
  for (const w of warnings) console.error(`  warn  ${w.message}`)

  if (!map.size) {
    console.error(
      `${warnings.length ? '' : '\n'}  error ${file} — no tokens found, and an empty ` +
      'document is never what you wanted. Nothing written.\n')
    return 1
  }

  /* A theme stylesheet names its theme in its own selector, so reading it back
     off `[data-theme="brand"]` costs the caller nothing. `--theme` overrides,
     and `:root` simply has no name to find — the document then carries none,
     and `largen theme` will ask for one when it reads this back. */
  const named = theme ?? selector.match(/\[data-theme=["']?([\w-]+)["']?\]/)?.[1] ?? null

  const { version } = JSON.parse(readFileSync(at('package.json'), 'utf8'))
  const doc = toDtcg(map, {
    version,
    theme: named,
    colorScheme,
    description: `Generated by \`largen tokens\` from ${file}.`,
  })

  const json = JSON.stringify(doc, null, 2) + '\n'
  if (out) writeFileSync(out, json)
  else process.stdout.write(json)

  const n = `${map.size} token${map.size === 1 ? '' : 's'}`
  const w = warnings.length ? `, ${warnings.length} warning${warnings.length === 1 ? '' : 's'}` : ''
  console.error(`\n  ${file} — ${n} from \`${selector}\`` +
    `${named ? `, theme "${named}"` : ''}${out ? ` -> ${out}` : ''}${w}\n`)
  return 0
}
